# Generated by Django 3.1.4 on 2020-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='locations_count',
            field=models.IntegerField(default=1, help_text='Количество локаций для игры НЕ МЕНЯТЬ!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='rating',
            field=models.IntegerField(help_text='Рейтинг режима. НЕ МЕНЯТЬ САМОМУ!'),
        ),
    ]
