# Generated by Django 3.1.4 on 2020-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20201219_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='likes',
            field=models.IntegerField(default=0, help_text='Сколько юзеров лайкнули локацию НЕ МЕНЯТЬ!'),
            preserve_default=False,
        ),
    ]
