# Generated by Django 3.1.4 on 2020-12-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_gamemode_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemode',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
