# Generated by Django 3.1.4 on 2020-12-19 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20201219_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
