# Generated by Django 3.1.4 on 2020-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20201220_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
