# Generated by Django 3.1.4 on 2020-12-27 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20201220_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModeClassic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название режима игры', max_length=200)),
                ('description', models.TextField(help_text='Краткое описание режима игры')),
                ('locations', models.TextField(help_text='доступные локации для игры в формате JSON + их описание')),
                ('locations_count', models.IntegerField(help_text='Количество локаций для игры НЕ МЕНЯТЬ!')),
                ('likes_count', models.IntegerField(help_text='Сколько юзеров лайкнули локацию НЕ МЕНЯТЬ!')),
                ('rating', models.IntegerField(help_text='Рейтинг режима. НЕ МЕНЯТЬ САМОМУ!')),
            ],
        ),
    ]
